spring.application.name=ecommerceofcourse

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerceofcourse_db
spring.datasource.username=postgres
spring.datasource.password=myNewPass531*
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jps.properties.hibernate.format_sql=true

server.port=8080
